# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c57cc2a80a941c9e20bcd4f80f704b801f2491ddfa01eb90b7b633e98200b5229754e3b9d228681df162e5bf3cf78caae5e74a94e928bf0ad7dbd5f0ffdc436

test:
  secret_key_base: efa4e20d2bfe7be6f59fe1e2065070ffa51cbdf34bb302d559f23eeda24eefb6f33e64c9578f3521ba1a9a9575538cf9f30165fd419cf564dbd017456f963596

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
